database:
  host: your_host # default: 127.0.0.1
  port: your_port # default: 3306
  username: your_user_name
  password: your_password
  dbname: your_db_name

redis:
  addr: your_addr # default: 127.0.0.1:6739
  password: your_password # default: ""
  db: your_db # default: 0

ipinfo:
  token: your_ipinfo.io_token
